### ISSUE TITLE
In General: Be more flexible with NBT detection

### ISSUE THREAD

**Issue by Sandstroem** [aaronhowser1/Infinity-Evolved-Expert-Mode-HQM#4]
This is more of a general issue I noticed, a lot of the quests are very strict when it comes to different variants of items.

For example:
I started in a birch forest, so I made my Tinkers Stuff out of Birch -> doesnt detect
I have seeds from villages with higher stats, some of them dont detect.

**Comment by aaronhowser1** [comment]
Yeah, this is on my to-do list. Right now, every task uses "NBT independent detection" (except the crops, which are "Fuzzy Detection") which is supposed to make that work, but some things don't. Using "Fuzzy detection" instead makes it so that any of the TiCon tables work, which isn't great. All of the TiCon tables are the same block id with different metadata; all of them are TConstruct:ToolStationBlock. There really isn't a good way for me to do this, it's an issue with the HQM mod itself as far as I can tell.

With the seeds, there's no way for a quest to be completed if you don't have the previous quests already done as well. The seed quests are supposed to guide you from vanilla plants to the Market or the Mystical Flowers, so I had to put them in order of what they are bred with.

**Comment by Sandstroem** [comment]
I might have posted both on the wrong github, those were supposed to be on the Infinity Evolved one, not the Skyblock, but I guess they might be valid for both.

**Comment by aaronhowser1** [comment]
This was posted on the non-skyblock one, don't worry. But yeah, this issue probably is in both, and I don't really know how to fix it, sorry.

**Comment by Sandstroem** [comment]
Well, the Tinkers stuff isnt really that important, it is just wood and I made a new one.

Players on our network reported especially the white, blue, red and yellow mystical flower seeds broken. Maybe they only detect 1-1-1, but those are hard to get if you crossbreed stuff.

**Comment by aaronhowser1** [comment]
All the seeds on the "Whole Foods" quest page are set to "Fuzzy Detection." I just tried spawning a bunch of different combinations for the Mystical Red Flower seed. I did 10/10/10, 9/4/5, and a bunch of other random number combos and they all worked (I reset the quest between tries. Even breeding a few in a creative world did it. Do they have the previous quests completed (as in, the Mystical seed quests are flashing)? Are you using the quests from the most recent official Infinity update, or from this Git page?
